export enum PtuLookupRange
{
    Ability = `'Abilities Data'!A3:Z`,
    Aura = `'Aura Data'!A3:Z`,
    Berry = `'Berry Data'!A2:Z`,
    Capability = `'Capability Data'!A2:Z`,
    Edge = `'Edges Data'!A2:Z`,
    Equipment = `'Equipment Data'!A3:Z`,
    EvolutionaryStone = `'Evolutionary Stone Data'!A2:Z`,
    Feature = `'Features Data'!A2:Z`,
    GiftBlessing = `'Legendary Gift / Blessing Data'!A3:Z`,
    Hazard = `'Hazard Data'!A2:Z`,
    HealingItem = `'Healing Item Data'!A2:Z`,
    HeldItem = `'Held Item Data'!A2:Z`,
    KeyItem = `'Key Item Data'!A3:Z`,
    Keyword = `'Keyword Data'!A2:Z`,
    Move = `'Moves Data'!A3:Z`,
    Nature = `'Nature Data'!A2:E`,
    Pokeball = `'Pokeball Data'!A2:Z`,
    Pokemon = `'Pokemon Data'!A3:AZ`,
    PokemonSkills = `'Pokemon Skills'!A2:AZ`,
    Status = `'Status Data'!A2:Z`,
    Tag = `'Tag Data'!A2:Z`,
    Terrain = `'Terrain Data'!A2:Z`,
    Tm = `'Tm Data'!A2:Z`,
    Vitamin = `'Vitamin Data'!A2:Z`,
    Weather = `'Weather Data'!A2:Z`,
    XItem = `'X-Item Data'!A2:Z`,
}

export enum PtuAutocompleteParameterName
{
    AbilityName = 'ability_name',
    Ability1 = 'ability_1',
    Ability2 = 'ability_2',
    Ability3 = 'ability_3',
    Ability4 = 'ability_4',
    AuraName = 'aura_name',
    AuraUserName = 'aura_user_name',
    BerryName = 'berry_name',
    CapabilityName = 'capability_name',
    ClassName = 'class_name',
    EdgeName = 'edge_name',
    EquipmentName = 'equipment_name',
    EvolutionaryStone = 'evolutionary_stone_name',
    FeatureName = 'feature_name',
    FemaleSpecies = 'female_species',
    GiftBlessingName = 'gift_blessing_name',
    GiftBlessingPatron = 'gift_blessing_patron',
    HazardName = 'hazard_name',
    HealingItem = 'healing_item_name',
    HeldItem = 'held_item_name',
    KeyItemName = 'key_item_name',
    KeywordName = 'keyword_name',
    MaleSpecies = 'male_species',
    MoveName = 'move_name',
    NatureName = 'nature_name',
    PokeballName = 'pokeball_name',
    PokemonName = 'pokemon_name',
    PokemonToEvolve = 'pokemon_to_evolve',
    StatusName = 'status_name',
    TagName = 'tag_name',
    TerrainName = 'terrain_name',
    TmName = 'tm_name',
    VitaminName = 'vitamin_name',
    WeatherName = 'weather_name',
    XItemName = 'x_item_name',
}
