export enum PtuSkill
{
    Acrobatics = 'Acrobatics',
    Athletics = 'Athletics',
    Charm = 'Charm',
    Combat = 'Combat',
    Command = 'Command',
    GeneralEducation = 'General Education',
    MedicineEducation = 'Medicine Education',
    OccultEducation = 'Occult Education',
    PokemonEducation = 'Pokemon Education',
    TechnologyEducation = 'Technology Education',
    Focus = 'Focus',
    Guile = 'Guile',
    Intimidate = 'Intimidate',
    Intuition = 'Intuition',
    Perception = 'Perception',
    Stealth = 'Stealth',
    Survival = 'Survival',
}
