export enum NwodAutocompleteParameterName
{
    ConditionName = 'condition_name',
    ClarityConditionTag = 'clarity_condition_tag',
    ConditionType = 'condition_type',
    ContractName = 'contract_name',
    DreadPowerName = 'dread_power_name',
    DreadPowerType = 'dread_power_type',
    GoblinFruitName = 'goblin_fruit_name',
    HauntName = 'haunt_name',
    KithName = 'kith_name',
    MementoName = 'memento_name',
    MeritName = 'merit_name',
    NeedleName = 'needle_name',
    NuminaName = 'numina_name',
    NuminaType = 'numina_type',
    RootAndBloomName = 'root_bloom_name',
    ThreadName = 'thread_name',
    TiltName = 'tilt_name',
    TokenName = 'token_name',
    WeaponName = 'weapon_name',
}

export enum NwodLookupRange
{
    Condition = `'Conditions Index'!A2:Z`,
    Contract = `'Changeling Contracts'!A2:Z`,
    DreadPower = `'Dread Power Reference'!A2:Z`,
    GoblinFruit = `'Goblin Fruit Index'!A3:Z`,
    Haunt = `'Haunt Powers Index'!A3:Z`,
    Kith = `'Kiths Index'!A2:Z`,
    Memento = `'Memento Index'!A3:Z`,
    Merit = `'Merits'!A2:Z`,
    Needle = `'Needle Archetype Reference'!A3:Z`,
    Numina = `'Numina Reference'!A2:Z`,
    RootAndBloom = `'Root and Bloom Index'!A3:Z`,
    Thread = `'Thread Archetype Reference'!A3:Z`,
    Tilt = `'Tilts Index'!A3:Z`,
    Token = `'Tokens Index'!A3:Z`,
    Weapon = `'Weapons Index'!A3:Z`,
}
