name: Clean Up Media Resources

on:
  schedule:
    - cron: '0 6 * * SAT'

jobs:
  clean-up-media-resources:
    runs-on: ubuntu-latest

    name: Clean Up Media Resources
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        env:
          GITHUB_PRIVATE_PACKAGES_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}
        run: npm install
      - name: Build
        run: npm run build
      - name: Clean Up Media Resources
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
          CLIENT_ID: ${{ secrets.BOT_CLIENT_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
          LOGGLY_TOKEN: ${{ secrets.LOGGLY_TOKEN }}
          LOGGLY_SUBDOMAIN: ${{ secrets.LOGGLY_SUBDOMAIN }}
          LOGGING_DISCORD_WEBHOOK: ${{ secrets.LOGGING_DISCORD_WEBHOOK }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
        run: npm run clean-up-media-resources
