name: Register Slash Commands

on:
  workflow_dispatch:
  push:
    branches: [
      main
    ]

jobs:
  register-slash-commands:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [
          18
        ]
    
    name: Register Slash Commands
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        env:
          GITHUB_PRIVATE_PACKAGES_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}
        run: npm install
      - name: Register Slash Commands
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
          CLIENT_ID: ${{ secrets.BOT_CLIENT_ID }}
          APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
          LOGGLY_TOKEN: ${{ secrets.LOGGLY_TOKEN }}
          LOGGLY_SUBDOMAIN: ${{ secrets.LOGGLY_SUBDOMAIN }}
          LOGGING_DISCORD_WEBHOOK: ${{ secrets.LOGGING_DISCORD_WEBHOOK }}
        run: npm run register-slash-commands
